language: ruby
sudo: false
cache: bundler
bundler_args: --without development
services:
  - postgresql
before_script:
  - psql -c 'create database "slash-gif_test";' -U postgres
rvm:
  - 2.3.1
  - 2.2.0
  - 2.1.2
  - 2.1.0
